language: node_js
node_js:
  - "10"

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run lint
  - npm run test-headless
  - ng build --prod --base-href https://thetostu.github.io/stardew-valley-helper/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/stardew-valley-helper
  on:
    branch: master
